name: Build

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish .\DesktopClock\DesktopClock.csproj -o "publish" -c Release -r win-x64

      - name: Create installer
        run: |
          dotnet tool install --global wix --version 4.0.3
          wix build Product.wxs -o "publish/Install DesktopClock.msi"
        
      - uses: actions/upload-artifact@v4
        with:
          path: |
            publish
