name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/prepare-for-release

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "publish/*.exe,publish/*.msi"
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: contains(github.ref, 'beta')
